version: '3.8'
services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
    command: make PYTHON=python run-all
    networks:
      - nyc-taxi-pipeline_default

networks:
  nyc-taxi-pipeline_default:
    external: true